# -*- coding: utf-8 -*-
"""Netflix chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1foMSDhBT2e1WhnUg1FtLpeuN7DCjCzbg
"""

pip install pandas gdown flask

import pandas as pd
import gdown
from flask import Flask, request, render_template_string

# Download the dataset from Google Sheets
google_sheet_url = 'https://docs.google.com/spreadsheets/d/1tEL1vbPHJulV7IdMekTsu7N8s6ufK-m4/export?format=csv&id=1tEL1vbPHJulV7IdMekTsu7N8s6ufK-m4'
output = 'netflix_data.csv'
gdown.download(google_sheet_url, output, quiet=False)

# Load the dataset
netflix_data = pd.read_csv(output)

# Define search functions
def search_by_title(title):
    results = netflix_data[netflix_data['name'].str.contains(title, case=False, na=False)]
    return results

def search_by_actor(actor):
    results = netflix_data[netflix_data['starring'].str.contains(actor, case=False, na=False)]
    return results

def search_by_genre(genre):
    results = netflix_data[netflix_data['genres'].str.contains(genre, case=False, na=False)]
    return results

def search_by_year(year):
    results = netflix_data[netflix_data['year'] == year]
    return results

# Initialize Flask app
app = Flask(__name__)

# Define the home page
@app.route('/')
def home():
    return '''
    <h1>Welcome to the Netflix Chatbot!</h1>
    <form action="/search" method="post">
        <label for="choice">Choose an option:</label>
        <select name="choice" id="choice">
            <option value="1">Search Movies by Title</option>
            <option value="2">Search Movies by Actor</option>
            <option value="3">Search Movies by Genre</option>
            <option value="4">Search Movies by Year</option>
        </select>
        <br><br>
        <label for="input">Enter your search term:</label>
        <input type="text" id="input" name="input" required>
        <br><br>
        <input type="submit" value="Search">
    </form>
    '''

# Define the search results page
@app.route('/search', methods=['POST'])
def search():
    choice = request.form['choice']
    user_input = request.form['input']
    if choice == '1':
        results = search_by_title(user_input)
    elif choice == '2':
        results = search_by_actor(user_input)
    elif choice == '3':
        results = search_by_genre(user_input)
    elif choice == '4':
        results = search_by_year(int(user_input))
    else:
        results = pd.DataFrame()

    if not results.empty:
        results_html = results[['name', 'starring', 'year', 'genres', 'country', 'describle']].to_html(index=False)
    else:
        results_html = '<p>No results found.</p>'

    return f'''
    <h1>Search Results</h1>
    {results_html}
    <br><br>
    <a href="/">Back to Home</a>
    '''

if __name__ == "__main__":
    app.run(debug=True)